---
title: "Tutorial Repro"
author: "Linus"
repro:
  scripts:
    - R/prepare_data.R
    - R/fun_cumulative.R
  data:
    xy: data/data.csv
  packages:
    - tidyverse
    - aaronpeikert/repro@adb5fa569
    - knitr
output: html_document
---

```{r}
library(repro) 
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# register external scripts and load packages and data (see YAML) 
automate_load_scripts() # to run R code in external scripts
automate_load_packages() # to execute chunks with R code
xy <- automate_load_data(xy, read_csv) 
```

# Analysis

Write functions for computing cumulative sums (means) and replacing `NAs` with the lagging value.

```{r fun_cumulative}
# writes function to compute cumulative sums
```

## Stats

Compute cumulative sums over y:

```{r}
# compute cumulative sums over y and print first 6 observations
xy %>% 
  mutate(y_cum = cumsum2(y)) %>% 
  head() %>% 
  kable()
```

## Plots

Show scatter plot of x and y:

```{r}
xy %>% 
  ggplot(aes(x, y)) + 
  geom_point() + 
  theme_minimal()
```
